// <auto-generated />
using System;
using Five7evens.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Five7evens.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Five7evens.API.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Guests")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Five7evens.API.Models.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BestTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BestTime = "April - June, September - October",
                            Description = "Experience the romantic charm of Paris, known as the City of Light. Walk through historic streets, admire world-famous art, and enjoy breathtaking views from iconic landmarks.",
                            Duration = "6 Hours",
                            Highlights = "Eiffel Tower, Louvre Museum, Seine River Cruise",
                            ImageUrl = "https://i.pinimg.com/1200x/98/51/0a/98510a0c6013f5913fac4b6d6c3aac12.jpg",
                            Name = "Paris, France",
                            Price = "$899",
                            Value = "paris"
                        },
                        new
                        {
                            Id = 2,
                            BestTime = "May - September",
                            Description = "Discover the tropical paradise of Bali, famous for its stunning beaches, lush landscapes, and rich cultural heritage.",
                            Duration = "5 Hours",
                            Highlights = "Beaches, Ubud Rice Terraces, Temples",
                            ImageUrl = "https://i.pinimg.com/736x/be/b8/09/beb8091eccec3bbbf2d4a9f0e722722b.jpg",
                            Name = "Bali, Indonesia",
                            Price = "$699",
                            Value = "bali"
                        },
                        new
                        {
                            Id = 3,
                            BestTime = "April - June, September - November",
                            Description = "Explore the vibrant energy of New York City, where culture, entertainment, and iconic sights come together.",
                            Duration = "7 Hours",
                            Highlights = "Statue of Liberty, Times Square, Central Park",
                            ImageUrl = "https://i.pinimg.com/736x/92/a1/a5/92a1a5bea064b5c48cc8b5bdee84de7b.jpg",
                            Name = "New York, USA",
                            Price = "$799",
                            Value = "nyc"
                        },
                        new
                        {
                            Id = 4,
                            BestTime = "March - May, October - November",
                            Description = "Immerse yourself in Tokyo's unique blend of tradition and modern innovation.",
                            Duration = "6 Hours",
                            Highlights = "Shibuya Crossing, Tokyo Tower, Sushi Experience",
                            ImageUrl = "https://i.pinimg.com/1200x/4a/0d/36/4a0d3638b7b0091d65a9c37fbb67f78e.jpg",
                            Name = "Tokyo, Japan",
                            Price = "$1099",
                            Value = "tokyo"
                        },
                        new
                        {
                            Id = 5,
                            BestTime = "April - June, September - October",
                            Description = "Step back in time in Rome, a city filled with ancient history and stunning architecture.",
                            Duration = "5 Hours",
                            Highlights = "Colosseum, Vatican City, Trevi Fountain",
                            ImageUrl = "https://i.pinimg.com/1200x/12/2b/26/122b26e0eae55ae80c5d076fef34576b.jpg",
                            Name = "Rome, Italy",
                            Price = "$849",
                            Value = "rome"
                        },
                        new
                        {
                            Id = 6,
                            BestTime = "November - March",
                            Description = "Experience luxury and innovation in Dubai, a city of futuristic skyscrapers and desert adventures.",
                            Duration = "6 Hours",
                            Highlights = "Burj Khalifa, Desert Safari, Dubai Mall",
                            ImageUrl = "https://i.pinimg.com/1200x/c2/c0/bb/c2c0bbc20e505f676efae924279029bb.jpg",
                            Name = "Dubai, UAE",
                            Price = "$999",
                            Value = "dubai"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
